EXCEPTION_TEMPLATE = "An exception of type {0} occurred. Arguments:\n{1!r}"

STANDALONE = 'local[*]'

BS = 16

DAY_PARTITION_FIELD_NAME = 'day'
SOFT_DELETED_FIELD_NAME = 'SOFT_DELETED'
DATE_IMPORTED_FIELD_NAME = 'DATE_IMPORTED'
YEAR_IMPORTED_FIELD_NAME = 'YEAR_IMPORTED'

ENTITY_NAME = 'entity_name'
DEFAULT_SAVE_LOCATION = 'default_save_location'
TEMP_SAVE_LOCATION = 'temp_save_location'
DEFAULT_SAVE_MODE = 'default_save_mode'
INCLUDE_DAY_PARTITION = 'include_day_partition'
FIELDS = 'fields'
FIELD_NAME = 'name'
FIELD_MAP_AS = 'map_as'
FIELD_TYPE = 'type'
FIELD_ENCRYPTION_KEY = 'encryption_key'
FIELD_IS_ENCRYPTED = 'is_encrypted'
SCENARIO_DELIMITER = 'delimiter'
SCENARIO_ID_FIELD = 'id_field'
SCENARIO_DEFAULT_SAVE_TYPE = 'default_save_type'
SCENARIO_TEMP_SAVE_LOCATION = 'temp_save_location'
SCENARIO_DEFAULT_SAVE_LOCATION = 'default_save_location'
SCENARIO_ENTITY_NAME = 'entity_name'
SCENARIO_DEFAULT_IMPORT_MODE = 'default_import_mode'
SCENARIO_HARD_DELETE_CONDITION_IN_YEARS = 'hard_delete_condition_in_years'
SCENARIO_ENFORCE_DATA_MODEL = 'enforce_data_model'
SCENARIO_IS_APPLY_YEAR_TO_SAVE_LOCATION = 'is_apply_year_to_save_location'

GENERIC_VALIDATE_RAW_VALUE_INDEX = 0
GENERIC_VALIDATE_SCENARIO_JSON_INDEX = 1
GENERIC_VALIDATE_COLUMN_NAME_INDEX = 2
GENERIC_VALIDATE_ROW_ID_VALUE_INDEX = 3

GENERIC_CRYPTO_VALUE_INDEX = 0
GENERIC_CRYPTO_COLUMN_INDEX = 1
GENERIC_CRYPTO_SCENARIO_INDEX = 2

GENERIC_SOFT_DELETE_ROW_VALUE_INDEX = 0
GENERIC_SOFT_DELETE_VALUE_T0_DELETE_INDEX = 1
GENERIC_SOFT_DELETED_VALUE_INDEX = 2
